name: Storybook

on: 
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v3
          - run: |
                git config --global user.name "Kiss Tamás"
                git config --global user.email "kiss.tamas.j@gmail.com"
          - run: |
                git getch
                git checkout Storybook
                git merge main --allow-unrelated-histories --no-ff -X theirs
          - run: |
                npm i
                npm run build-storybook
                rm -rf docs
                mv storybook-static docs
          - run: |
                git add .
                git commit -m "storybook update"
                git push